config/routes.rb
Rails.application.routes.draw do

  resources :tags, only: [:new, :create, :show, :edit, :update], path: "e"
  resources :print_button_clicks, only: [:create]
  resources :tag_makers, only: [:new, :create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "tag_makers#new"
  # Defines the root path route ("/")
  # root "posts#index"
  mount Blazer::Engine, at: "blazer"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/print_button_click.rb
class PrintButtonClick < ApplicationRecord
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  attribute :meses_proxima_troca_oleo_motor, default: "6"
  attribute :km_proxima_troca_filtro_oleo, default: I18n.t("PRÓXIMA")
  attribute :km_proxima_troca_filtro_ar_motor, default: I18n.t("PRÓXIMA")
  attribute :km_proxima_troca_filtro_ar_condicionado, default: I18n.t("PRÓXIMA")
  attribute :km_proxima_troca_filtro_oleo_combustivel, default: I18n.t("PRÓXIMA")
  attribute :km_proxima_troca_diferencial, default: I18n.t("PRÓXIMA")
  attribute :km_proxima_troca_oleo_cambio, default: I18n.t("PRÓXIMA")
  attribute :km_proxima_troca_fluido_radiador, default: I18n.t("PRÓXIMA")
  attribute :km_proxima_troca_oleo_freio, default: I18n.t("PRÓXIMA")
  attribute :km_proximo_alinhamento, default: I18n.t("PRÓXIMA")
  attribute :km_proxima_troca_fluido_direcao, default: I18n.t("PRÓXIMA")
  attribute :km_proximo_balanceamento, default: I18n.t("PRÓXIMA")
  def generate_zpl
    ZplGenerator.new.generate_tag_zpl(self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/print_button_clicks_controller.rb
class PrintButtonClicksController < ApplicationController
  def create
    PrintButtonClick.create! tag_id: params[:tag_id]
  end
end

app/controllers/tag_makers_controller.rb
class TagMakersController < ApplicationController
  def new
    @tag_maker = TagMaker.new
  end

  def create
    @tag_maker = TagMaker.new(**tag_maker_params)
    if @tag_maker.valid?
      @tag = @tag_maker.create_tag
      redirect_to edit_tag_path(@tag)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def tag_maker_params
    checkbox_fields = %i[
      alinhamento balanceamento diferencial f_direcao filt_ar_cond
      filt_ar_motor filt_comb filt_oleo fluido_radiador oleo_cambio oleo_freio
    ]

    permitted_params = params.require(:tag_maker).permit(
      :nome_cliente, :placa_carro, :telefone, :numero_pedido_bling,
      :km_atual, :enviar_lembrete_apos, :km_proxima_troca, :tipo_cambio,
      *checkbox_fields
    )

    infos = permitted_params.to_hash.symbolize_keys

    checkbox_fields.each do |field|
      infos[field] = infos[field] == "1" if infos.key?(field)
    end

    infos[:km_atual] = infos[:km_atual].gsub(/[.]/, '')

    infos
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController


  def new
    @tag = Tag.new
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      flash[:notice] = "Etiqueta salva com sucesso!"
      redirect_to @tag
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      flash[:notice] = "Etiqueta salva com sucesso!"
      redirect_to tag_path(@tag)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(
      :placa_carro, :nome_cliente, :nome_mecanico, :telefone, :km_atual,
      :oleo_utilizado, :km_proxima_troca_oleo_motor, :meses_proxima_troca_oleo_motor,
      :km_proxima_troca_filtro_oleo, :km_proxima_troca_filtro_ar_motor,
      :km_proxima_troca_filtro_ar_condicionado, :km_proxima_troca_filtro_oleo_combustivel,
      :km_proxima_troca_diferencial, :km_proxima_troca_oleo_cambio,
      :km_proxima_troca_fluido_radiador, :km_proxima_troca_oleo_freio,
      :km_proximo_alinhamento, :km_proximo_balanceamento,
      :km_proxima_troca_fluido_direcao, :numero_pedido_bling, :lembrar_cliente_em
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/print_button_clicks_helper.rb
module PrintButtonClicksHelper
end

app/helpers/tag_builder_helper.rb
module TagBuilderHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Etiquetas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <script src="/bpmin.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/print_button_clicks/create.html.erb
<div>
  <h1 class="font-bold text-4xl">PrintButtonClicks#create</h1>
  <p>Find me in app/views/print_button_clicks/create.html.erb</p>
</div>

app/views/tag_makers/create.html.erb
<div>
  <h1 class="font-bold text-4xl">TagBuilder#create</h1>
  <p>Find me in app/views/tag_builder/create.html.erb</p>
</div>

app/views/tag_makers/new.html.erb
<div class="p-10">

  <%= form_with scope: :tag_maker, id: "tag_maker_form", url: tag_makers_path do |f| %>
  
    <div>
      <div>
        <%= f.label :nome_cliente, t('Nome do cliente') %>
        <%= f.text_field :nome_cliente, class: "block h-9" %>
      </div>

      <div class="mt-4 flex gap-8">
        <div>
          <%= f.label :placa_carro, t("Placa") %>
          <%= f.text_field :placa_carro, class: "block h-9" %>
        </div>

        <div>
          <%= f.label :telefone, t("Telefone") %>
          <%= f.text_field :telefone, class: "block h-9" %>
        </div>
      </div>

      <div class="mt-4">
        <%= f.label :numero_pedido_bling, t("Número pedido Bling") %>
        <%= f.text_field :numero_pedido_bling, class: "block h-9" %>
      </div>
      
    </div>

    <div>

      <div class="flex gap-8">
        <div class="mt-10">
          <%= f.label :km_atual, t("Quilometragem Atual") %>
          <%= f.text_field :km_atual, class: "block h-9" %>

          <div class="text-red-600 h-10"><%= @tag_maker.errors[:km_atual] %></div>
        </div>

        <div class="mt-10">

          <div><%= t('Lembrar cliente em')%></div>
          <div class="mt-2 flex gap-x-8">
            <label>
              <%= f.radio_button :enviar_lembrete_apos, t("1 mês") %>
              <%=t('1 mês')%>
            </label>
            <label>
              <%= f.radio_button :enviar_lembrete_apos, t("3 meses") %>
              <%=t('3 meses')%>
            </label>
            <label>
              <%= f.radio_button :enviar_lembrete_apos, t("6 meses") %>
              <%=t('6 meses')%>
            </label>
            
          </div>
        </div>
      </div>

      <div class="mt-6 font-semibold"><%=t('Próxima troca de óleo do motor após')%></div>
      <div class="flex gap-x-8 items-center">
        <div class="mt-2">
          <%= f.radio_button :km_proxima_troca, "5000", data: { controller: "hotkey", hotkey: "5" } %>
          <%= f.label :km_proxima_troca_5000, "#{number_with_delimiter(5000)} km" %>
        </div>
        <div class="mt-2">
          <%= f.radio_button :km_proxima_troca, "7500", data: { controller: "hotkey", hotkey: "7" } %>
          <%= f.label :km_proxima_troca_7500, "#{number_with_delimiter(7500)} km" %>
        </div>
        <div class="mt-2">
          <%= f.radio_button :km_proxima_troca, "10000", data: { controller: "hotkey", hotkey: "1 0" } %>
          <%= f.label :km_proxima_troca_10000, "#{number_with_delimiter(10000)} km" %>
        </div>
        
      </div>

      <div class="mt-6 font-semibold"><%= t('Serviços realizados') %></div>

      <div class="flex gap-x-10">

        <div>
          <div class="flex items-center w-42 mt-2">
            <%= f.check_box "alinhamento", class: "mr-2" , data: { controller: "hotkey", hotkey: "a l" } %>
            <%= f.label :alinhamento, t('Alinhamento') %>
          </div>

          <div class="flex items-center w-42 mt-2">
            <%= f.check_box "balanceamento", class: "mr-2", data: { controller: "hotkey", hotkey: "b a" } %>
            <%= f.label :balanceamento, t('Balanceamento') %>
          </div>

          <div class="flex items-center w-42 mt-2">
            <%= f.check_box "diferencial", class: "mr-2", data: { controller: "hotkey", hotkey: "d i" } %>
            <%= f.label :diferencial, t("Diferencial") %>
          </div>

          <div class="flex items-center w-42 mt-2">
            <%= f.check_box "f_direcao", class: "mr-2", data: { controller: "hotkey", hotkey: "f d" } %>
            <%= f.label :f_direcao, t("Fluido de direção") %>
          </div>
        </div>

        <div>
          <div class="flex items-center w-42 mt-2">
            <%= f.check_box "filt_ar_cond", class: "mr-2" %>
            <%= f.label :filt_ar_cond, t('Filtro do ar condicionado') %>
          </div>

          <div class="flex items-center w-42 mt-2">
            <%= f.check_box "filt_ar_motor", class: "mr-2" %>
            <%= f.label :filt_ar_motor, t('Filtro de ar do motor') %>
          </div>

          <div class="flex items-center w-42 mt-2">
            <%= f.check_box "filt_comb", class: "mr-2" %>
            <%= f.label :filt_comb, t("Filtro do combustível") %>
          </div>

          <div class="flex items-center w-42 mt-2">
            <%= f.check_box "filt_oleo", class: "mr-2" %>
            <%= f.label :filt_oleo, t("Filtro de óleo") %>
          </div>
        </div>

        <div>
          <div class="flex items-center w-42 mt-2">
            <%= f.check_box "fluido_radiador", class: "mr-2" %>
            <%= f.label :fluido_radiador, t("Fluido radiador") %>
          </div>

          <div class="flex items-center w-42 mt-2">
            <%= f.check_box "oleo_cambio", class: "mr-2" %>
            <%= f.label :oleo_cambio, t("Óleo de câmbio") %>
          </div>

          <div class="flex items-center w-42 mt-2">
            <%= f.check_box "oleo_freio", class: "mr-2" %>
            <%= f.label :oleo_freio, t("Óleo de freio") %>
          </div>
        </div>
      </div>

      <div class="mt-6 font-semibold"><%= t('Tipo do câmbio') %></div>
      <div class="flex items-center w-42 mt-2 gap-x-4">
        <div>
          <label>
            <%= f.radio_button :tipo_cambio, TagMaker::TRANSMISSION_TYPES[:automatic] %>
            <%= t('Automático') %>
          </label>
        </div>

        <div>
          <label>
            <%= f.radio_button :tipo_cambio, TagMaker::TRANSMISSION_TYPES[:manual] %>
            <%= t('Manual') %>
          </label>
        </div>
      </div>
      <div class="h-10 text-red-600"><%= @tag_maker.errors[:tipo_cambio] %></div>
    </div>
    <div>
      <%= f.submit t("Montar etiqueta"), class: "cursor-pointer p-2 bg-green-300 mt-8" %>
    </div>

  <% end %>

</div>

app/views/tags/_form.html.erb
<%= form_with model: tag do |f| %>
  <div class="m-20 w-[60rem] text-lg uppercase">
    <div>
      <div>
        <%= f.label :nome_cliente, t("Nome do cliente") %>
        <%= f.text_field :nome_cliente, class: "block h-9" %>
      </div>

      <div class="mt-4 flex gap-8">
        <div>
          <%= f.label :placa_carro, t('Placa') %>
          <%= f.text_field :placa_carro, class: "block h-9" %>
        </div>

        <div>
          <%= f.label :telefone, t('Telefone') %>
          <%= f.text_field :telefone, class: "block h-9" %>
        </div>
      </div>

      <div class="flex gap-x-8">
        <div class="mt-4">
          <%= f.label :numero_pedido_bling, t('Número pedido Bling') %>
          <%= f.text_field :numero_pedido_bling, class: "block h-9" %>
        </div>

        <div class="mt-4">
          <%= f.label :lembrar_cliente_em, t('Lembrar cliente em') %>
          <%= f.text_field :lembrar_cliente_em, class: "block h-9" %>
        </div>

      </div>

      
    </div>

    <div class="mt-10">
      <p class=" ml-24"><span class="inline-block w-80 border-b-2 border-b-black pb-0 text-center text-lg font-semibold"><%= l(Date.new(Time.now.year, Time.now.month, Time.now.day)) %></span></p>

      <p class=" ml-9"><%= t('com') %> 
        <%= f.text_field :km_atual, class: "inline-block w-40 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold" %> km t:
        <%= f.text_field :nome_mecanico, class: "inline-block w-40 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold" %>
      </p>

      <p><%= t('óleo') %> <%= f.text_field :oleo_utilizado, class: "inline-block w-[26rem] border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold" %> </p>

      <p class="ml-44 mt-2"><%= t('próxima troca') %></p>

      <p><%= t('óleo motor') %> <%= f.text_field :km_proxima_troca_oleo_motor, class: "inline-block w-40 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold" %> km <%= t('ou') %> <%= f.text_field :meses_proxima_troca_oleo_motor, class: "inline-block w-24 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold" %> <%= t('meses') %></p>

      <p class="ml-8"><%= t('filt óleo') %> <%= f.text_field :km_proxima_troca_filtro_oleo, class: "inline-block w-40 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold" %> <%= t('filt ar motor') %> <%= f.text_field :km_proxima_troca_filtro_ar_motor, class: "inline-block w-40 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold" %></p>
      
      <p class="ml-16"><%= t('filt ar cond') %> <%= f.text_field :km_proxima_troca_filtro_ar_condicionado, class: "inline-block w-40 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold" %> <%= t('filt comb') %> <%= f.text_field :km_proxima_troca_filtro_oleo_combustivel, class: "inline-block w-40 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold" %></p>

      <p class="ml-20"><%= t('diferencial') %> <%= f.text_field :km_proxima_troca_diferencial, class: "inline-block w-40 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold" %> <%= t('óleo cambio') %> <%= f.text_field :km_proxima_troca_oleo_cambio, class: "inline-block w-40 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold" %></p>

      <p class="ml-24"><%= t('fluido radiador') %> <%= f.text_field :km_proxima_troca_fluido_radiador, class: "inline-block w-40 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold" %> <%= t('óleo freio') %> <%= f.text_field :km_proxima_troca_oleo_freio, class: "inline-block w-40 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold" %></p>
      
      <p class="ml-36"><%= t('alinhamento') %> <%= f.text_field :km_proximo_alinhamento, class: "inline-block w-40 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold" %> <%= t('direção') %> <%= f.text_field :km_proxima_troca_fluido_direcao, class: "inline-block w-40 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold" %></p>

      <p class="ml-64 "><%= t('balanceamento') %> <%= f.text_field :km_proximo_balanceamento, class: "inline-block w-40 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold" %> </p>
    </div>
    <div class="ml-72 mt-10">
      <%= f.submit t("Salvar"), class: "bg-blue-200 p-2 cursor-pointer" %>
    </div>
  </div>
<% end %>

app/views/tags/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Tags#create</h1>
  <p>Find me in app/views/tags/create.html.erb</p>
</div>

app/views/tags/edit.html.erb
<div class="text-2xl font-semibold pt-6 pl-20"><%= t('Nova Etiqueta') %></div>

<%= render "form", tag: @tag %>

app/views/tags/new.html.erb
<div class="text-2xl font-semibold pt-6 pl-20"><%= t('Nova Etiqueta') %></div>

<%= render "form", tag: @tag %>

app/views/tags/show.html.erb
  <div class="ml-20 mt-10 text-lg underline">
    <a href=<%= new_tag_maker_path %>><%= t('Criar uma nova etiqueta')%></a>
    <div>
      <%= link_to t('Editar esta etiqueta'), edit_tag_path(@tag) %>
    </div>
  </div>
  
  <div class="m-20 w-[60rem] text-lg uppercase">
    <div class="mt-10">
      <p class=" ml-24"><span class="inline-block w-96 border-b-2 border-b-black pb-0 text-center text-lg font-semibold"><%= l(Date.new(Time.now.year, Time.now.month, Time.now.day)) %></span></p>

      <p class="ml-9"> <%= t('com') %> 
       <span class="inline-block w-40 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold"> <%= @tag.km_atual %> </span> km t:
       <span class="inline-block w-40 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold"> <%= @tag.nome_mecanico %> </span>
      </p>

       <p><%=t('óleo')%> <span class="inline-block w-[26rem] border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold"> <%= @tag.oleo_utilizado %> </span> </p>

       <p class="ml-44 mt-2"><%= t('próxima troca')%></p>

       <p><%= t('óleo motor') %> <span class="inline-block w-40 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold"> <%= @tag.km_proxima_troca_oleo_motor %> </span> km <%= t('ou') %> <span class="inline-block w-24 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold"> <%= @tag.meses_proxima_troca_oleo_motor %> </span> <%= t('meses') %></p>

       <p class="ml-8"><%= t('filt óleo') %> <span class="inline-block w-40 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold"> <%= @tag.km_proxima_troca_filtro_oleo %> </span> <%= t('filt ar motor') %> <span class="inline-block w-40 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold"> <%= @tag.km_proxima_troca_filtro_ar_motor %> </span></p>

       <p class="ml-16"><%= t('filt ar cond') %><span class="inline-block w-40 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold"> <%= @tag.km_proxima_troca_filtro_ar_condicionado %> </span> <%= t('filt comb') %> <span class="inline-block w-40 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold"> <%= @tag.km_proxima_troca_filtro_oleo_combustivel  %> </span></p>

       <p class="ml-20"><%= t('diferencial') %><span class="inline-block w-40 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold"> <%= @tag.km_proxima_troca_diferencial %> </span> <%= t('óleo cambio') %> <span class="inline-block w-40 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold"> <%= @tag.km_proxima_troca_oleo_cambio %> </span></p>

       <p class="ml-24"><%= t('fluido radiador') %><span class="inline-block w-40 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold"> <%= @tag.km_proxima_troca_fluido_radiador %> </span> <%= t('óleo freio') %><span class="inline-block w-40 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold"> <%= @tag.km_proxima_troca_oleo_freio %> </span></p>

       <p class="ml-36"><%= t('alinhamento') %><span class="inline-block w-40 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold"> <%= @tag.km_proximo_alinhamento %> </span><%= t('direcao') %><span class="inline-block w-40 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold"> <%= @tag.km_proxima_troca_fluido_direcao %> </span></p>

       <p class="ml-64"><%= t('balanceamento') %><span class="inline-block w-40 border-0 border-b-2 border-b-black pb-0 text-center text-lg font-semibold"> <%= @tag.km_proximo_balanceamento %></span> </p>
    </div>
    <div class="ml-72 mt-10">
      <button data-controller="encrenca"
              data-action="encrenca#print"
              data-encrenca-tag-param="<%= @tag.id %>"
              class="bg-blue-200 p-3 cursor-pointer" 
        data-encrenca-zpl-param='<%= @tag.generate_zpl %>'><%= t('Imprimir') %></button>
    </div>
  </div>
    